<a href="https://colab.research.google.com/github/madham32/Recommender_System/blob/master/ML_Project_with_recommendations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install tensorflow-gpu

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
from google.colab import files
files.upload()  #this will prompt you to upload the kaggle.json

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"madham32","key":"00fdd0fe19b3203692987b435b287ad9"}'}

In [0]:
!pip install -q kaggle
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!ls ~/.kaggle
!chmod 600 /root/.kaggle/kaggle.json  # set permission

kaggle.json


In [0]:
!kaggle datasets download -d netflix-inc/netflix-prize-data -p /content/gdrive/My\ Drive/kaggle/netflix

In [0]:
import os
os.chdir('gdrive/My Drive/kaggle/netflix')  #change dir

# !unzip netflix-prize-data.zip


In [4]:
import csv
import pandas as pd
from keras.models import Sequential
from keras.layers import Input, Embedding, Flatten, Dot, Dense, Concatenate, Activation, Reshape

Using TensorFlow backend.


In [0]:
i=0
probe_file1=open('combined_data_1.txt','r') 
probe_file2=open('combined_data_2.txt','r') 
probe_file3=open('combined_data_3.txt','r') 
probe_file4=open('combined_data_4.txt','r') 

new_file=open('NEW_probe_data.txt','w')

def add_data(probefile, newfile, i):
    
    for line in probefile:
        if ':' in line:
            i+=1
            continue
        line=line.strip()+','+str(i)+'\n'
        newfile.write(line) 
    return i
    

i=add_data(probe_file1, new_file, i)
print(i)
i=add_data(probe_file2, new_file, i)
print(i)
i=add_data(probe_file3, new_file, i)
print(i)
i=add_data(probe_file4, new_file, i)
print(i)

In [0]:
data = pd.read_csv( "NEW_probe_data.txt", header=0, 
 delimiter=",", quoting=3,names=['user_id','rating','timestamp','movie_id'] )

In [0]:
data

user_id  rating   timestamp  movie_id
0           822109       5  2005-05-13         1
1           885013       4  2005-10-19         1
2            30878       4  2005-12-26         1
3           823519       3  2004-05-03         1
4           893988       3  2005-11-17         1
5           124105       4  2004-08-05         1
6          1248029       3  2004-04-22         1
7          1842128       4  2004-05-09         1
8          2238063       3  2005-05-11         1
9          1503895       4  2005-05-19         1
10         2207774       5  2005-06-06         1
11         2590061       3  2004-08-12         1
12            2442       3  2004-04-14         1
13          543865       4  2004-05-28         1
14         1209119       4  2004-03-23         1
15          804919       4  2004-06-10         1
16         1086807       3  2004-12-28         1
17         1711859       4  2005-05-08         1
18          372233       5  2005-11-23         1
19         1080361       3  2005-03-28         1
20         1245640       3  2005-12-19         1
21          558634       4  2004-12-14         1
22         2165002       4  2004-04-06         1
23         1181550       3  2004-02-01         1
24         1227322       4  2004-02-06         1
25          427928       4  2004-02-26         1
26          814701       5  2005-09-29         1
27          808731       4  2005-10-31         1
28          662870       5  2005-08-24         1
29          337541       5  2005-03-23         1
...            ...     ...         ...       ...
100479745   423607       2  2004-06-13     17770
100479746   382234       3  2005-07-27     17770
100479747   366939       3  2004-03-02     17770
100479748  1180066       4  2004-08-27     17770
100479749   645237       4  2004-09-21     17770
100479750  2235640       3  2004-12-20     17770
100479751    66958       3  2005-04-04     17770
100479752  1912002       3  2005-09-21     17770
100479753  1918520       1  2005-12-17     17770
100479754  2439493       1  2003-11-22     17770
100479755  1382766       1  2004-06-20     17770
100479756  1422981       2  2005-06-04     17770
100479757  2226594       4  2004-01-08     17770
100479758  2583311       3  2004-02-04     17770
100479759  2249491       4  2004-11-18     17770
100479760   543507       4  2005-04-05     17770
100479761   566255       1  2005-05-07     17770
100479762   620229       4  2003-11-25     17770
100479763   983389       4  2004-02-18     17770
100479764  1457186       3  2004-02-11     17770
100479765  1542673       3  2004-02-25     17770
100479766   609742       4  2004-11-07     17770
100479767  1255271       3  2005-04-21     17770
100479768  1100765       1  2005-07-14     17770
100479769  1509293       3  2003-12-03     17770
100479770   925510       3  2004-12-22     17770
100479771  2185614       2  2005-02-05     17770
100479772  1308960       1  2003-12-02     17770
100479773  1659023       2  2004-01-13     17770
100479774   361375       3  2004-03-24     17770

[100479775 rows x 4 columns]

In [0]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(data, test_size=0.2, random_state=42)

In [0]:
n_users = len(data.user_id.unique())

n_movies = len(data.movie_id.unique())


In [0]:
# creating book embedding path
movie_input = Input(shape=[1], name="Movie-Input")
movie_embedding = Embedding(n_movies+1, 4, name="Movie-Embedding")(movie_input)
movie_vec = Flatten(name="Flatten-Movies")(movie_embedding)

# creating user embedding path
user_input = Input(shape=[1], name="User-Input")
user_embedding = Embedding(n_users+1, 4, name="User-Embedding")(user_input)
user_vec = Flatten(name="Flatten-Users")(user_embedding)

# performing dot product and creating model
prod = Dot(name="Dot-Product", axes=1)([movie_vec, user_vec])
model = Model([user_input, movie_input], prod)
model.compile('adam', 'mean_squared_error')

In [0]:
from keras.models import Model


# creating book embedding path
movie_input = Input(shape=[1], name="Movie-Input")
movie_embedding = Embedding(n_movies+1, 5, name="Movie-Embedding")(movie_input)
movie_vec = Flatten(name="Flatten-Movies")(movie_embedding)

# creating user embedding path
user_input = Input(shape=[1], name="User-Input")
user_embedding = Embedding(n_users+1, 5, name="User-Embedding")(user_input)
user_vec = Flatten(name="Flatten-Users")(user_embedding)

# concatenate features
conc = Concatenate()([movie_vec, user_vec])

# add fully-connected-layers
fc1 = Dense(128, activation='relu')(conc)
fc2 = Dense(32, activation='relu')(fc1)
out = Dense(1)(fc2)

# Create model and compile it
model2 = Model([user_input, movie_input], out)
model2.compile('adam', 'mean_squared_error')

Instructions for updating:
Colocations handled automatically by placer.


In [17]:

from keras.models import load_model

if os.path.exists('regression_model2.h5'):
    model2 = load_model('regression_model2.h5')
else:
    history = model2.fit([train.user_id, train.movie_id], train.rating, epochs=2, verbose=1)
    model2.save('regression_model2.h5')


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [0]:
history.history['loss']

NameError: ignored

In [33]:
import numpy as np


# Creating dataset for making recommendations for the first user
movie_data = np.array(list(set(data.movie_id)))
movie_data[:5]


user = np.array([1 for i in range(len(movie_data))])
user[:5]


[1 2 3 4 5]


In [46]:

predictions = model2.predict([user, movie_data])

predictions = np.array([a[0] for a in predictions])

recommended_movie_ids = (-predictions).argsort()[:5]

recommended_movie_ids

array([ 8075,  5658,  3455,  7229, 14960])

In [23]:
predictions[recommended_movie_ids]

array([15.407293 , 14.199906 ,  4.7365074,  4.735477 ,  4.7207274],
      dtype=float32)

In [0]:
model2.evaluate([test.user_id, test.movie_id], test.rating)

20095955/20095955 [==============================] - 810s 40us/step


0.9935715879386653

In [68]:
movies = pd.read_csv('movie_titles_new.csv', names=['movie_id', 'release_year', 'movie_title' ])
movies.head()

movie_id  release_year                   movie_title
0         1        2003.0               Dinosaur Planet
1         2        2004.0    Isle of Man TT 2004 Review
2         3        1997.0                     Character
3         4        1994.0  Paula Abdul's Get Up & Dance
4         5        2004.0      The Rise and Fall of ECW

In [69]:
movies[movies['movie_id'].isin(recommended_movie_ids)]


movie_id  release_year                        movie_title
3454       3455        2002.0                       Time Changer
5657       5658        2001.0                     The Experiment
7228       7229        1968.0      Pippi Longstocking: TV Series
8074       8075        2000.0  The Last of the Blonde Bombshells
14959     14960        1986.0                       Three Amigos